### ISSUE TITLE
incomplete dependencies

### ISSUE THREAD

**Issue by cknoll** [xolox/python-preview-markup#1]
On my machine (Debian 9.1): In order to run preview-markup in addidition to `pip install preview-markup` I had to run two extra commands:

- `sudo apt install libffi-dev`
- `pip install coloredlogs`

Error message associated with first problem:

> pip install preview-markup
...
Collecting preview-markup
  Downloading preview-markup-0.3.tar.gz
Collecting BeautifulSoup>=3.2.1 (from preview-markup)
  Downloading BeautifulSoup-3.2.1.tar.gz
Collecting Flask>=0.10.1 (from preview-markup)
  Using cached Flask-0.12.2-py2.py3-none-any.whl
Requirement already satisfied: Pygments>=1.6 in /usr/local/lib/python2.7/dist-packages (from preview-markup)
Requirement already satisfied: docutils>=0.12 in /usr/local/lib/python2.7/dist-packages (from preview-markup)
Collecting humanfriendly>=1.14 (from preview-markup)
  Downloading humanfriendly-4.4.1-py2.py3-none-any.whl (64kB)
    100% |████████████████████████████████| 71kB 2.7MB/s 
Collecting misaka>=1.0.2 (from preview-markup)
  Downloading misaka-2.1.0.tar.gz (127kB)
    100% |████████████████████████████████| 133kB 2.7MB/s 
    Complete output from command python setup.py egg_info:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    c/_cffi_backend.c:15:17: fatal error: ffi.h: Datei oder Verzeichnis nicht gefunden
     #include <ffi.h>
                     ^
    compilation terminated.

Error message associated with second problem:

> preview-markup 
Traceback (most recent call last):
  File "/usr/local/bin/preview-markup", line 7, in <module>
    from preview_markup.cli import main
  File "/usr/local/lib/python2.7/dist-packages/preview_markup/cli.py", line 24, in <module>
    import coloredlogs
ImportError: No module named coloredlogs

**Comment by xolox** [comment]
Hi @cknoll and thanks for pointing this out. I've added `coloredlogs` to the installation requirements and I added a mention of the `libffi-dev` system package to the readme. Release 0.3.2 contains the updated installation requirements.
